env:
    global:
        - "PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'"
        # pip dependencies to _test_ your project
        - TEST_DEPENDS="numpy==1.11.1"
        # params to bdist_wheel. used to set osx build target.
        - BDIST_PARAMS=""
        - CONFIG_PATH="travis_config.sh"
        - USE_CCACHE=1
        - UNICODE_WIDTH=32
        - MB_PYTHON_VERSION=3.7

# Host Python is never used
language: generic
services: docker
# https://docs.travis-ci.com/user/reference/xenial
dist: xenial

# Save some time, we and setup check them out on demand instead
# https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth
git:
    submodules: false

# https://docs.travis-ci.com/user/caching
cache:
  directories:
    # `cache: ccache: true` has no effect if `language:` is not `c` or `cpp`
    - $HOME/.ccache

# Add more cache stages (s2 etc) and corresponding OSX jobs like s1
# if brew builds start to take longer than one Travis time limit
stages:
  - s1
  - final

matrix:
  fast_finish: true
  include:

    - os: osx
      osx_image: xcode8.3
      stage: s1
      workspaces:
        create:
          name: brew_cache
          paths:
            # https://stackoverflow.com/questions/39930171/cache-brew-builds-with-travis-ci
            - $HOME/Library/Caches/Homebrew
            - /usr/local/Homebrew/
            # used in OSX custom build script dealing with local bottle caching
            - $HOME/local_bottle_metadata
      #workspaces share within the same build, cache shares between builds
      cache:
        directories:
          # `cache: ccache: true` has no effect if `language:` is not `c` or `cpp`
          - $HOME/.ccache
          # https://stackoverflow.com/questions/39930171/cache-brew-builds-with-travis-ci
          - $HOME/Library/Caches/Homebrew
          - /usr/local/Homebrew/
          # used in OSX custom build script dealing with local bottle caching
          - $HOME/local_bottle_metadata

    # default builds for MacOS
      #further jobs in the list will use the same stage until the next assignment
    # - stage: final
    #   os: osx
    #   osx_image: xcode8.3
    #   env:
    #     - MB_PYTHON_VERSION=3.6
    #     - ENABLE_CONTRIB=0
    #     - ENABLE_HEADLESS=0
    #   workspaces:
    #     use: brew_cache
    # - os: osx
    #   osx_image: xcode8.3
    #   env:
    #     - MB_PYTHON_VERSION=3.7
    #     - ENABLE_CONTRIB=0
    #     - ENABLE_HEADLESS=0
    #     - TEST_DEPENDS=numpy==1.14.5
    #   workspaces:
    #     use: brew_cache
    # - os: osx
    #   osx_image: xcode8.3
    #   env:
    #     - MB_PYTHON_VERSION=3.8
    #     - ENABLE_CONTRIB=0
    #     - ENABLE_HEADLESS=0
    #     - TEST_DEPENDS=numpy==1.17.3
    #   workspaces:
    #     use: brew_cache
    #
    # # headless builds for MacOS
    # - os: osx
    #   osx_image: xcode8.3
    #   env:
    #     - MB_PYTHON_VERSION=3.6
    #     - ENABLE_CONTRIB=0
    #     - ENABLE_HEADLESS=1
    #   workspaces:
    #     use: brew_cache
    # - os: osx
    #   osx_image: xcode8.3
    #   env:
    #     - MB_PYTHON_VERSION=3.7
    #     - ENABLE_CONTRIB=0
    #     - ENABLE_HEADLESS=1
    #     - TEST_DEPENDS=numpy==1.14.5
    #   workspaces:
    #     use: brew_cache
    # - os: osx
    #   osx_image: xcode8.3
    #   env:
    #     - MB_PYTHON_VERSION=3.8
    #     - ENABLE_CONTRIB=0
    #     - ENABLE_HEADLESS=1
    #     - TEST_DEPENDS=numpy==1.17.3
    #   workspaces:
    #     use: brew_cache
    #
    # # Contrib builds for MacOS
    # - os: osx
    #   osx_image: xcode8.3
    #   env:
    #     - MB_PYTHON_VERSION=3.6
    #     - ENABLE_CONTRIB=1
    #     - ENABLE_HEADLESS=0
    #   workspaces:
    #     use: brew_cache
    # - os: osx
    #   osx_image: xcode8.3
    #   env:
    #     - MB_PYTHON_VERSION=3.7
    #     - ENABLE_CONTRIB=1
    #     - ENABLE_HEADLESS=0
    #     - TEST_DEPENDS=numpy==1.14.5
    #   workspaces:
    #     use: brew_cache
    # - os: osx
    #   osx_image: xcode8.3
    #   env:
    #     - MB_PYTHON_VERSION=3.8
    #     - ENABLE_CONTRIB=1
    #     - ENABLE_HEADLESS=0
    #     - TEST_DEPENDS=numpy==1.17.3
    #   workspaces:
    #     use: brew_cache
    #
    # # headless contrib builds for MacOS
    # - os: osx
    #   osx_image: xcode8.3
    #   env:
    #     - MB_PYTHON_VERSION=3.6
    #     - ENABLE_CONTRIB=1
    #     - ENABLE_HEADLESS=1
    #   workspaces:
    #     use: brew_cache
    # - os: osx
    #   osx_image: xcode8.3
    #   env:
    #     - MB_PYTHON_VERSION=3.7
    #     - ENABLE_CONTRIB=1
    #     - ENABLE_HEADLESS=1
    #     - TEST_DEPENDS=numpy==1.14.5
    #   workspaces:
    #     use: brew_cache
    # - os: osx
    #   osx_image: xcode8.3
    #   env:
    #     - MB_PYTHON_VERSION=3.8
    #     - ENABLE_CONTRIB=1
    #     - ENABLE_HEADLESS=1
    #     - TEST_DEPENDS=numpy==1.17.3
    #   workspaces:
    #     use: brew_cache

    # default builds for Linux
    # - os: linux
    #   env:
    #     - MB_PYTHON_VERSION=3.6
    #     - ENABLE_CONTRIB=0
    #     - ENABLE_HEADLESS=0
    #     - TEST_DEPENDS=numpy==1.11.3
    #   cache:
    #     directories: $HOME/.ccache
    # - os: linux
    #   env:
    #     - MB_PYTHON_VERSION=3.6
    #     - PLAT=i686
    #     - ENABLE_CONTRIB=0
    #     - ENABLE_HEADLESS=0
    #     - TEST_DEPENDS=numpy==1.11.3
    #   cache:
    #     directories: $HOME/.ccache
    # - os: linux
    #   env:
    #     - MB_PYTHON_VERSION=3.7
    #     - ENABLE_CONTRIB=0
    #     - ENABLE_HEADLESS=0
    #     - TEST_DEPENDS=numpy==1.14.5
    #   cache:
    #     directories: $HOME/.ccache
    # - os: linux
    #   env:
    #     - MB_PYTHON_VERSION=3.7
    #     - PLAT=i686
    #     - ENABLE_CONTRIB=0
    #     - ENABLE_HEADLESS=0
    #     - TEST_DEPENDS=numpy==1.14.5
    #   cache:
    #     directories: $HOME/.ccache
    # - os: linux
    #   env:
    #     - MB_PYTHON_VERSION=3.8
    #     - ENABLE_CONTRIB=0
    #     - ENABLE_HEADLESS=0
    #     - TEST_DEPENDS=numpy==1.17.3
    #   cache:
    #     directories: $HOME/.ccache
    # - os: linux
    #   env:
    #     - MB_PYTHON_VERSION=3.8
    #     - PLAT=i686
    #     - ENABLE_CONTRIB=0
    #     - ENABLE_HEADLESS=0
    #     - TEST_DEPENDS=numpy==1.17.3
    #   cache:
    #     directories: $HOME/.ccache
    #
    # # headless builds for Linux
    # - os: linux
    #   env:
    #     - MB_PYTHON_VERSION=3.6
    #     - ENABLE_CONTRIB=0
    #     - ENABLE_HEADLESS=1
    #     - TEST_DEPENDS=numpy==1.11.3
    #   cache:
    #     directories: $HOME/.ccache
    # - os: linux
    #   env:
    #     - MB_PYTHON_VERSION=3.6
    #     - PLAT=i686
    #     - ENABLE_CONTRIB=0
    #     - ENABLE_HEADLESS=1
    #     - TEST_DEPENDS=numpy==1.11.3
    #   cache:
    #     directories: $HOME/.ccache
    # - os: linux
    #   env:
    #     - MB_PYTHON_VERSION=3.7
    #     - ENABLE_CONTRIB=0
    #     - ENABLE_HEADLESS=1
    #     - TEST_DEPENDS=numpy==1.14.5
    #   cache:
    #     directories: $HOME/.ccache
    # - os: linux
    #   env:
    #     - MB_PYTHON_VERSION=3.7
    #     - PLAT=i686
    #     - ENABLE_CONTRIB=0
    #     - ENABLE_HEADLESS=1
    #     - TEST_DEPENDS=numpy==1.14.5
    #   cache:
    #     directories: $HOME/.ccache
    # - os: linux
    #   env:
    #     - MB_PYTHON_VERSION=3.8
    #     - ENABLE_CONTRIB=0
    #     - ENABLE_HEADLESS=1
    #     - TEST_DEPENDS=numpy==1.17.3
    #   cache:
    #     directories: $HOME/.ccache
    # - os: linux
    #   env:
    #     - MB_PYTHON_VERSION=3.8
    #     - PLAT=i686
    #     - ENABLE_CONTRIB=0
    #     - ENABLE_HEADLESS=1
    #     - TEST_DEPENDS=numpy==1.17.3
    #   cache:
    #     directories: $HOME/.ccache

    # contrib builds for Linux
    - stage: final
      os: linux
    # - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
        - TEST_DEPENDS=numpy==1.11.3
        - ENABLE_CONTRIB=1
        - ENABLE_HEADLESS=0
      cache:
        directories: $HOME/.ccache
    # - os: linux
    #   env:
    #     - MB_PYTHON_VERSION=3.6
    #     - PLAT=i686
    #     - TEST_DEPENDS=numpy==1.11.3
    #     - ENABLE_CONTRIB=1
    #     - ENABLE_HEADLESS=0
    #   cache:
    #     directories: $HOME/.ccache
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
        - TEST_DEPENDS=numpy==1.14.5
        - ENABLE_CONTRIB=1
        - ENABLE_HEADLESS=0
      cache:
        directories: $HOME/.ccache
    # - os: linux
    #   env:
    #     - MB_PYTHON_VERSION=3.7
    #     - PLAT=i686
    #     - TEST_DEPENDS=numpy==1.14.5
    #     - ENABLE_CONTRIB=1
    #     - ENABLE_HEADLESS=0
    #   cache:
    #     directories: $HOME/.ccache
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
        - TEST_DEPENDS=numpy==1.17.3
        - ENABLE_CONTRIB=1
        - ENABLE_HEADLESS=0
      cache:
        directories: $HOME/.ccache
    # - os: linux
    #   env:
    #     - MB_PYTHON_VERSION=3.8
    #     - PLAT=i686
    #     - TEST_DEPENDS=numpy==1.17.3
    #     - ENABLE_CONTRIB=1
    #     - ENABLE_HEADLESS=0
    #   cache:
    #     directories: $HOME/.ccache


    # headless contrib builds for Linux
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
        - TEST_DEPENDS=numpy==1.11.3
        - ENABLE_CONTRIB=1
        - ENABLE_HEADLESS=1
      cache:
        directories: $HOME/.ccache
    # - os: linux
    #   env:
    #     - MB_PYTHON_VERSION=3.6
    #     - PLAT=i686
    #     - TEST_DEPENDS=numpy==1.11.3
    #     - ENABLE_CONTRIB=1
    #     - ENABLE_HEADLESS=1
    #   cache:
    #     directories: $HOME/.ccache
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
        - TEST_DEPENDS=numpy==1.14.5
        - ENABLE_CONTRIB=1
        - ENABLE_HEADLESS=1
      cache:
        directories: $HOME/.ccache
    # - os: linux
    #   env:
    #     - MB_PYTHON_VERSION=3.7
    #     - PLAT=i686
    #     - TEST_DEPENDS=numpy==1.14.5
    #     - ENABLE_CONTRIB=1
    #     - ENABLE_HEADLESS=1
    #   cache:
    #     directories: $HOME/.ccache
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
        - TEST_DEPENDS=numpy==1.17.3
        - ENABLE_CONTRIB=1
        - ENABLE_HEADLESS=1
      cache:
        directories: $HOME/.ccache
    # - os: linux
    #   env:
    #     - MB_PYTHON_VERSION=3.8
    #     - PLAT=i686
    #     - TEST_DEPENDS=numpy==1.17.3
    #     - ENABLE_CONTRIB=1
    #     - ENABLE_HEADLESS=1
    #   cache:
    #     directories: $HOME/.ccache

# The first line is printed in the folding header in Travis output
before_install: |
    # Check out and prepare the source
    set -e
    # Multibuild doesn't have releases, so --depth would break eventually (see
    # https://superuser.com/questions/1240216/server-does-not-allow-request-for-unadvertised)
    git submodule update --init multibuild
    echo "Source multibuild/common_utils.sh"
    source multibuild/common_utils.sh
    # https://github.com/matthew-brett/multibuild/issues/116
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export ARCH_FLAGS=" "; fi
    echo "Source multibuild/travis_steps.sh"
    source multibuild/travis_steps.sh
    # This sets -x
    echo "Source travis_multibuild_customize.sh"
    source travis_multibuild_customize.sh
    echo $ENABLE_CONTRIB > contrib.enabled
    echo $ENABLE_HEADLESS > headless.enabled

    if [ -n "$IS_OSX" ]; then
        echo "homebrew"
        TAPS="$(brew --repository)/Library/Taps"
        if [ -e "$TAPS/caskroom/homebrew-cask" -a -e "$TAPS/homebrew/homebrew-cask" ]; then
            rm -rf "$TAPS/caskroom/homebrew-cask"
        fi
        find "$TAPS" -type d -name .git -exec \
                bash -xec '
                    cd $(dirname '\''{}'\'') || echo "status: $?"
                    git clean -fxd || echo "status: $?"
                    sleep 1 || echo "status: $?"
                    git status || echo "status: $?"' \; || echo "status: $?"

        brew_cache_cleanup
    fi
    echo "end"
    # Not interested in travis internal scripts' output
    set +x

install: |
    # Build and package
    set -x
    build_wheel $REPO_DIR $PLAT
    set +x

script: |
    # Install and run tests
    set -x
    install_run $PLAT && rc=$? || rc=$?
    set +x

    #otherwise, Travis logic terminates prematurely
    #https://travis-ci.community/t/shell-session-update-command-not-found-in-build-log-causes-build-to-fail-if-trap-err-is-set/817
    trap ERR

    test "$rc" -eq 0

before_cache: |
    # Cleanup dirs to be cached
    set -e; set -x
    if [ -n "$IS_OSX" ]; then

        # When Taps is cached, this dir causes "Error: file exists" on `brew update`
        if [ -e "$(brew --repository)/Library/Taps/homebrew/homebrew-cask/homebrew-cask" ]; then
            rm -rf "$(brew --repository)/Library/Taps/homebrew/homebrew-cask/homebrew-cask"
        fi

        brew_cache_cleanup

    fi
    set +x; set +e
